CREATE TABLE DEPARTMENT
(
    DEPTCODE INT PRIMARY KEY,
    DeptName CHAR(30) UNIQUE,
    LOCATION VARCHAR(33) NOT NULL
);

CREATE TABLE EMPLOYEE
(
    EmpCode    INT PRIMARY KEY,
    EmpFName   VARCHAR(15),
    EmpLName   VARCHAR(15),
    Job        VARCHAR(45),
    Manager    CHAR(4),
    HireDate   DATE,
    Salary     DECIMAL(6, 2),
    Commission INT,
    DEPTCODE   INT,
    CONSTRAINT fk_Dept FOREIGN KEY (`DEPTCODE`) REFERENCES `DEPARTMENT` (`DEPTCODE`) ON DELETE CASCADE
);