server:
  port: 8081
  servlet:
    context-path: /rdb
spring:
  application:
    name: "Redis Database app"
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      username: default
      password: cachepass01
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: